### ISSUE TITLE
I suggest adding Timings Paper

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/FoxServer#3]
If I'm not mistaken it's called **Timings v2**
![image](https://user-images.githubusercontent.com/86433158/162280158-cfb68152-81bc-423a-8a1b-c614e6d76051.png)
It's more comfortable than the Spigot version.

**Comment by Kotori0629** [comment]
Why not use spark?

**Comment by XionioXMaster** [comment]
> Why not use spark?

I suggested this as an alternative to the old Spigot variant, although yes Spark is also good if you understand it.

**Comment by Kotori0629** [comment]
> > Why not use spark?
> 
> I suggested this as an alternative to the old Spigot variant, although yes Spark is also good if you understand it.

Think about it....
