### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by UeberallGebannt** [Luohuayu/FoxServer#4]
Would you please be so kind and give credit to Magma and Mohist if you're stealing their code? :)

**Comment by Luohuayu** [comment]
What is stealing? Some code is under the GPL agreement and the source is marked

**Comment by UeberallGebannt** [comment]
> What is stealing? Some code is under the GPL agreement and the source is marked

I wasnt able to find any line saying "hey this is from Mohist".
You only inserted one line saying that you modified Magma code.

**Comment by Kotori0629** [comment]
> > What is stealing? Some code is under the GPL agreement and the source is marked
> 
> I wasnt able to find any line saying "hey this is from Mohist". You only inserted one line saying that you modified Magma code.

It's only from Magma. What's the problem? which code is from Mohist? Huh?

**Comment by UeberallGebannt** [comment]
@Kotori0629 Since your commands seems to have "vanished", let me post it again here:
![grafik](https://user-images.githubusercontent.com/50475262/162632240-4e042269-dd0e-449d-9192-936e87755929.png)

There is Mohist code in this repo, I looked at the code with a Mohist dev and he confirmed it.
Second, you say that the code is from Magma, why do you only give credit for one class then? It has to be easy to see for everyone that the code is from Magma. Just writing ONE line in ONE class isn't enough.

**Comment by UeberallGebannt** [comment]
This file is a plain copy of Mohist. It isn't even included in Magma's repo
https://github.com/Luohuayu/FoxServer/blob/1.18.2-dev/patches/minecraft/com/mojang/realmsclient/gui/screens/RealmsGenericErrorScreen.java.patch

I'm sure there are much more files, this took me literally 20 seconds to find.

**Comment by Luohuayu** [comment]
It mean Forge is stealing code from FoxServer/Magma/Mohist?
lol
https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/CrashReport.java.patch
