### ISSUE TITLE
:angry: :tired_face: 

### ISSUE THREAD

**Issue by Hexeption** [Luohuayu/FoxServer#5]
Just why do china have to steal eveything?

**Comment by XionioXMaster** [comment]
> Just why do china have to steal eveything?
![image](https://user-images.githubusercontent.com/86433158/162621635-8a3fa5b5-f848-4934-984a-ae594ec9fca0.png)

**Comment by Kotori0629** [comment]
You can choose not to open source

**Comment by UeberallGebannt** [comment]
> > Just why do china have to steal eveything?
> > ![image](https://user-images.githubusercontent.com/86433158/162621635-8a3fa5b5-f848-4934-984a-ae594ec9fca0.png)

Kind of hilarious how you have to give a heart reaction to your own comment because nobody else does xD

**Comment by UeberallGebannt** [comment]
> You can choose not to open source

Open source doesn't allow stealing code without credit :)

**Comment by XionioXMaster** [comment]
> > > Just why do china have to steal eveything?
> > > ![image](https://user-images.githubusercontent.com/86433158/162621635-8a3fa5b5-f848-4934-984a-ae594ec9fca0.png)
> 
> Kind of hilarious how you have to give a heart reaction to your own comment because nobody else does xD

yes-yes

**Comment by Luohuayu** [comment]
Why do you oepn source with LPGL?
https://github.com/magmafoundation/Magma-1.18.x/blob/master/LICENSE.txt

**Comment by Luohuayu** [comment]
Some people, if they continue to be unreasonable, I will block
