### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by TheOriginalGolem** [Luohuayu/FoxServer#6]
The **_Big Issue_**, it that you are not giving proper credit to either mohist or magma. It doesn't matter that you have used their code, the problem is that there is basically no credit for the borrowed code used. Its a really simple fix :/

**Comment by TheOriginalGolem** [comment]
You labeling this as spam says everything about you. Rather than taking the time to correct the issue, you'd rather just sweep it under a rug.

**Comment by Kotori0629** [comment]
There is no need to cover up, and soon they will no longer exist
